MyQuickStartApp/Models/QuarterToDateSalesViewModel.cs
using System;

namespace KendoQsBoilerplate
{
    public class QuarterToDateSalesViewModel
    {
        public int OrderID { get; set; }
        public DateTime OrderDate { get; set; }
        public decimal Current { get; set; }
        public decimal Target { get; set; }
    }
}

MyQuickStartApp/Controllers/HomeController.cs
using KendoQsBoilerplate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;

public class HomeController : Controller
{
    private readonly NorthwindDBContext db = new NorthwindDBContext();
    public ActionResult Index()
    {
        return View();
    }

    #region Quick Start Primer
    // These methods were added to assist with the quickstart guide.
    private IEnumerable<MonthlySalesByEmployeeViewModel> EmployeeAverageSalesQuery(int employeeId, DateTime statsFrom, DateTime statsTo)
    {
        return (from allSales in
                           (from o in db.Orders
                            join od in db.Order_Details on o.OrderID equals od.OrderID
                            where o.EmployeeID == employeeId && o.OrderDate >= statsFrom && o.OrderDate <= statsTo
                            select new
                            {
                                EmployeeID = o.EmployeeID,
                                Date = o.OrderDate,
                                Sales = od.Quantity * od.UnitPrice
                            }
                               ).ToList()
                group allSales by new DateTime(allSales.Date.Value.Year, allSales.Date.Value.Month, 1) into g
                select new MonthlySalesByEmployeeViewModel
                {
                    EmployeeID = g.FirstOrDefault().EmployeeID,
                    EmployeeSales = g.Sum(x => x.Sales),
                    Date = g.Key,
                }
        );
    }

    private IEnumerable<QuarterToDateSalesViewModel> EmployeeQuarterSalesQuery(int employeeId, DateTime statsTo, DateTime startDate)
    {
        var sales = db.Orders.Where(w => w.EmployeeID == employeeId)
            .Join(db.Order_Details, orders => orders.OrderID, orderDetails => orderDetails.OrderID, (orders, orderDetails) => new { Order = orders, OrderDetails = orderDetails })
            .Where(d => d.Order.OrderDate >= startDate && d.Order.OrderDate <= statsTo).ToList()
            .Select(o => new QuarterToDateSalesViewModel
            {
                Current = (o.OrderDetails.Quantity * o.OrderDetails.UnitPrice) - (o.OrderDetails.Quantity * o.OrderDetails.UnitPrice * (decimal)o.OrderDetails.Discount)
            });
        //TODO: Generate the target based on team's average sales
        return new List<QuarterToDateSalesViewModel>() {
                     new QuarterToDateSalesViewModel {Current = sales.Sum(s=>s.Current), Target = 15000, OrderDate = statsTo}
            };
    }
    public ActionResult EmployeesList_Read([DataSourceRequest]DataSourceRequest request)
    {
        var employees = db.Employees.OrderBy(e => e.FirstName);
        return Json(employees.ToDataSourceResult(request, ModelState), JsonRequestBehavior.AllowGet);
    }

    public ActionResult EmployeeQuarterSales(int employeeId, DateTime statsTo)
    {
        DateTime startsDate = statsTo.AddMonths(-3);
        var result = EmployeeQuarterSalesQuery(employeeId, statsTo, startsDate);
        return Json(result, JsonRequestBehavior.AllowGet);
    }

    protected override void Dispose(bool disposing)
    {
        db.Dispose();
        base.Dispose(disposing);
    }
    #endregion
}

MyQuickStartApp/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using KendoQsBoilerplate;

namespace MyQuickStartApp.Controllers
{
    public class InvoiceController : Controller
    {
        private NorthwindDBContext db = new NorthwindDBContext();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Invoices_Read([DataSourceRequest]DataSourceRequest request, string salesPerson)
        {
            IQueryable<Invoice> invoices = db.Invoices.Where(inv => inv.Salesperson == salesPerson);
            DataSourceResult result = invoices.ToDataSourceResult(request, invoice => new
            {
                OrderID = invoice.OrderID,
                CustomerName = invoice.CustomerName,
                OrderDate = invoice.OrderDate,
                ProductName = invoice.ProductName,
                UnitPrice = invoice.UnitPrice,
                Quantity = invoice.Quantity,
                Salesperson = invoice.Salesperson,
            });

            return Json(result);
        }

        [HttpPost]
        public ActionResult Excel_Export_Save(string contentType, string base64, string fileName)
        {
            var fileContents = Convert.FromBase64String(base64);

            return File(fileContents, contentType, fileName);
        }

        [HttpPost]
        public ActionResult Pdf_Export_Save(string contentType, string base64, string fileName)
        {
            var fileContents = Convert.FromBase64String(base64);

            return File(fileContents, contentType, fileName);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MyQuickStartApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MyQuickStartApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MyQuickStartApp/Views/Home/Index.cshtml
@using Prototyping.Ipsum
@using Prototyping.Placeholdit
@{
    ViewBag.Title = "Team Efficiency";
}

<section id="app-title-bar" class="row">
    <div class="col-sm-3">
        <h1 class="title">@ViewBag.Title</h1>
    </div>
</section>

<div class="app-wrapper">
    <!-- Menu Panel -->
    <div class="hidden-xs" style="float:left;">
        <h3>Report Range</h3>
        <p>@Html.Label("Stats from")</p>
        <p>
            <!-- Stats From Date Picker -->
            @(Html.Kendo().DatePicker()
            .Name("StatsFrom")
                .Value(new DateTime(1996, 1, 1))
                .Events(e => e.Change("onCriteriaChange"))
            )
        </p>
        <p>@Html.Label("Stats to")</p>
        <p>
            <!-- Stats To Date Picker -->
            @(Html.Kendo().DatePicker()
                                                                                    .Name("StatsTo")
                                                                                    .Value(new DateTime(1998, 8, 1))
                                                                                     .Events(e => e.Change("onCriteriaChange"))
            )
        </p>
        <nav id="employee-list">
            <h3>Team members</h3>
            <!-- Employee List View -->
            @(Html.Kendo().ListView<KendoQsBoilerplate.Employee>()
                                                                            .Name("EmployeesList")
                                                                            .ClientTemplateId("EmployeeItemTemplate")
                                                                            .TagName("ul")
                                                                            .DataSource(dataSource =>
                                                                            {
                                                                                dataSource.Read(read => read.Action("EmployeesList_Read", "Home"));
                                                                            })
                                    .Selectable(s => s.Mode(ListViewSelectionMode.Single))
                                    .Events(e => e.DataBound("onListDataBound").Change("onCriteriaChange"))

            )
        </nav>
    </div>
    <!-- /Menu Panel -->

    <section id="main-section-content" class="row">
        <article class="col-xs-12">
            <div id="employee-details" class="row">
                <div id="employee-about" class="col-xs-12 col-lg-4">

                </div>
                <div class="col-xs-12 col-lg-4">
                    <div class="chart-wrap">
                        <h3 class="chart-title">Quarter to date sales</h3>
                        <p class="sales-report-value" id="EmployeeQuarterSalesLabel"></p>
                        @Html.Partial("_QuarterToDateSales")
                    </div>
                </div>
                <div class="col-xs-12 col-lg-4">
                    <div class="chart-wrap">
                        <h3 class="chart-title">Monthly Average Sales</h3>
                        <p class="sales-report-value" id="EmployeeAverageSalesLabel"></p>
                        <!-- Montly Sales Chart -->
                        @Html.Placehold(430, 120, "Chart")
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <h3>Representative orders</h3>
                    <!-- Invoices -->
                    @Html.Action("Index", "Invoice")
                </div>
            </div>
        </article>
    </section>
</div>

<!-- Kendo Templates -->
<script type="text/x-kendo-tmpl" id="EmployeeItemTemplate">
    <li class="employee">
        <div>
            <img src="@(Url.Content("~/content/employees/"))#: EmployeeId#-t.png" />
            <span>#: FullName #</span>
        </div>
    </li>
</script>
<script type="text/x-kendo-tmpl" id="EmployeeAvatarTemplate">
    <img src="@(Url.Content("~/content/employees/"))#: EmployeeId#.png" />
    <span>#: FullName #</span>
</script>
<!-- /Kendo Templates -->

@section Scripts {
    <script>
        //Custom Scripts

        function onListDataBound(e) {
            this.select($(".employee:first"));
        }

        function getSelectedEmployee() {
            var employeeList = $('#EmployeesList').data('kendoListView');
            var employee = employeeList.dataSource.getByUid(employeeList.select().attr('data-uid'));
            return employee;

        }

        function updateEmployeeAvatar() {
            var employee = getSelectedEmployee();
            var template = kendo.template($('#EmployeeAvatarTemplate').html());
            $('#employee-about').html(template(employee));
        }

        function onCriteriaChange() {
            updateEmployeeAvatar();
            refreshGrid();
            refreshEmployeeQuarterSales();
        }

        function getEmployeeFilter() {
            var employee = getSelectedEmployee(),
                statsFrom = $('#StatsFrom').data('kendoDatePicker'),
                statsTo = $('#StatsTo').data('kendoDatePicker');
            var filter = {
                employeeId: employee.EmployeeId,
                salesPerson: employee.FullName,
                statsFrom: statsFrom.value(),
                statsTo: statsTo.value()
            };
            return filter;
        }

        function refreshGrid() {
            var employeeSales = $('#EmployeeSales').data('kendoGrid');
            employeeSales.dataSource.read();
        }

        function refreshEmployeeQuarterSales() {
            var employeeQuarterSales = $('#employeeQuarterSales').data('kendoChart');
            employeeQuarterSales.dataSource.read();
        }
    </script>
}

MyQuickStartApp/Views/Home/_QuarterToDateSales.cshtml
@(Html.Kendo().Chart<KendoQsBoilerplate.QuarterToDateSalesViewModel>
        ()
        .Name("EmployeeQuarterSales")
        .HtmlAttributes(new { style = "height:30px;" })

        .Series(seriers =>
        {
            seriers.Bullet(model => model.Current, model => model.Target);
        })
        .CategoryAxis(ca => ca.Labels(lab => lab.Visible(false))
        .MajorGridLines(m => m.Visible(false).Visible(false))
        )
        .ValueAxis(va => va.Numeric()
        .Labels(l => l.Visible(false))
        .MajorGridLines(m => m.Visible(false))
        .MajorTicks(mT => mT.Visible(false))
        )
        .Legend(leg => leg.Visible(false))
        .DataSource(ds => ds
            .Read(read => read.Action("EmployeeQuarterSales", "Home")
            .Data("getEmployeeFilter"))
        )

        .AutoBind(false)
)